version: '3'

services:
  nginx-proxy:
    build:
      context: ./nginx-proxy
    env_file:
      - ./.env/.env
    restart: always
    links:
      - webapp
      - webapi
    ports:
      - 80:80
      - 443:443
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./data/logs/nginx-proxy:/var/log/nginx

  webapp:
    build:
      context: .
      dockerfile: ./nodejs/Dockerfile
    env_file:
      - ./.env/.env
    environment:
      VIRTUAL_HOST: localhost
      VIRTUAL_PORT: 8080
      CERT_NAME: localhost
      HTTPS_METHOD: noredirect
    expose:
        - 8080
    ports:
      - 8000:8080
    volumes:
      - ./data/html/app:/app

  webapi:
    build:
      context: .
      dockerfile: ./nginx/Dockerfile
      args:
        NGINX_VERSION: alpine
    env_file:
      - ./.env/.env
    environment:
      VIRTUAL_HOST: api.localhost
      CERT_NAME: localhost
      HTTPS_METHOD: noredirect
    links:
      - apiapp
    volumes:
      - ./nginx/conf/conf.d/api.conf:/etc/nginx/conf.d/default.conf
      - ./data/logs/nginx/api:/var/log/nginx
      - ./data/html/api:/var/www/html


  apiapp:
    build:
      context: .
      dockerfile: ./php-fpm/Dockerfile
      args:
        PHP_IMAGE_VERSION: 7-fpm-alpine
    ports:
      - 9000:9000
    env_file:
      - ./.env/.env
    depends_on:
      - db
    volumes:
      - ./data/html/api:/var/www/html
      # - ./.env/codeigniter4.env:/var/www/html/.env

  db:
    image: mariadb:latest
    ports:
      - 3306:3306
    expose:
      - 3306
    env_file:
      - ./.env/.env
    environment:
      MYSQL_DATABASE: app
      MYSQL_USER: db_user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password
    volumes:
      - db-data:/var/lib/mysql
      - ./mariadb/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
      - ./mariadb/my.cnf:/etc/mysql/conf.d/my.cnf

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    ports:
      - 8080:80
    env_file:
      - ./.env/.env
    environment:
      PMA_HOST: db
      PMA_USER: root
      PMA_PASSWORD: password
    links:
      - db
    volumes:
      - ./phpmyadmin/config/config.inc.php:/etc/phpmyadmin/config.user.inc.php

volumes:
  db-data:
